### Register a new user
POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
    "email": "susan@gmail.com",
    "full_name": "Susan Amechi",
    "role": "student",
    "password": "password123"
}